package client.resources;

import java.util.ListResourceBundle;

public class Languages_da_DA extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"auth.authorizationHeaderLabel", "Tilladelse"},
                {"lang.denmarkLanguageMenuItem", "Dansk"},
                {"lang.englishLanguageMenuItem", "Engelsk"},
                {"lang.languageMenu", "Sprog"},
                {"auth.loginTextField", "Indtast dit brugernavn..."},
                {"auth.passwordPasswordField", "Indtast adgangskoden..."},
                {"auth.portBindingButton", "Tilslutte"},
                {"lang.russianLanguageMenuItem", "Russisk"},
                {"lang.turkishLanguageMenuItem", "Tyrkisk"},
                {"auth.loginTextField", "Indtast dit brugernavn..."},
                {"auth.authButton", "Log pÃÂ¥"},
                {"main.menu.addNewTicket", "TilfÃÂ¸j ny billet"},
                {"main.menu.clearCollection", "Ryd samling"},
                {"main.menu.countTicketsThat", "TÃÂ¦l billetter med en rabat mindre end..."},
                {"main.menu.printDiscount", "Udskriv alle rabatvÃÂ¦rdier"},
                {"main.menu.uniquePrice", "Unikke prisvÃÂ¦rdier"},
                {"main.menu.infoAboutCollection", "Indsamlingsoplysninger"},
                {"main.commandMenu", "Hold"},
                {"main.helpMenu", "HjÃÂ¦lp"},
                {"main.help.help", "Udskriv kommandoliste"},
                {"main.filterByColumnLabel", "Sorter efter:"},
                {"main.refreshTableButton", "Opdater"},
                {"main.currentUserLabel", "NuvÃÂ¦rende bruger:"},
                {"edit.header", "Billetredigering"},
                {"edit.ticketName", "Billetnavn:"},
                {"edit.ticketX", "X-koordinaten"},
                {"edit.ticketY", "Y-koordinaten"},
                {"edit.ticketPrice", "Pris"},
                {"edit.ticketDiscount", "Rabat"},
                {"edit.ticketType", "billettype"},
                {"edit.eventName", "Begivenhedsnavn"},
                {"edit.eventDate", "Begivenhedsdato"},
                {"edit.eventMinAge", "Minimumsalder"},
                {"edit.eventDescription", "Beskrivelse af begivenheden"},
                {"edit.eventType", "Begivenhedstype"},
                {"edit.saveTicketIfMinButton", "Gem hvis billetten er minimal"},
                {"edit.saveTicketButton", "Gem billet"},
                {"edit.alerts.blankFieldError", "Det ser ud til, at du ikke har udfyldt alle formularfelterne. PrÃÂ¸v igen."},
                {"edit.ticketComment", "En kommentar"},
                {"auth.alerts.authError", "Godkendelsesfejl"},
                {"main.alerts.error", "Der opstod en fejl "},
                {"main.alerts.success", "Succesfuldt!"},
                {"main.collectionType", "Samlingstype"},
                {"main.initializationDate", "Initialiseringsdato: "},
                {"main.itemsQuantity", "MÃÂ¦ngde af elementer:"},
                {"main.alerts.discountQuantity", "Indtast rabatvÃÂ¦rdi: "},
                {"main.alerts.notNumber", "VÃÂ¦rdien er ikke et tal!"},
                {"main.alerts.discountError", "VÃÂ¦rdien passer ikke inden for rabatomrÃÂ¥det"},
                {"main.ticketEditing", "Billetskift"},
                {"main.alerts.fieldsError", "Nogle formularfelter er udfyldt forkert."},
                {"main.mainWindow", "Hovedvindue"},
                {"auth.alerts.serverConnectionError", "Der opstod en fejl under forbindelse til serveren "},
                {"auth.alerts.serverConnectionSuccess", "Forbindelsen til serveren lykkedes!"},
                {"auth.serverConnection", "Serverforbindelse"},
                {"drawing.windowTitle", "Visualisering af den aktuelle tilstand"},
                {"main.menu.changeUserColors", "Opdater bordfarver"},
                {"edit.deleteTicketButton", "Slet"},
        };
    }
}
