package client.resources;

import java.util.ListResourceBundle;

public class Languages_tr_TR extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"auth.authorizationHeaderLabel", "Yetkilendirme"},
                {"lang.denmarkLanguageMenuItem", "DanimarkalÄ±"},
                {"lang.englishLanguageMenuItem", "Ä°ngiliz"},
                {"lang.languageMenu", "Dil"},
                {"auth.loginTextField", "GiriÅ bilgilerinizi girin..."},
                {"auth.passwordPasswordField", "Åifreyi girin..."},
                {"auth.portBindingButton", "BaÄlan"},
                {"lang.russianLanguageMenuItem", "Rus"},
                {"lang.turkishLanguageMenuItem", "TÃ¼rk"},
                {"auth.authButton", "GiriÅ yapmak"},
                {"main.menu.addNewTicket", "Yeni bilet ekle"},
                {"main.menu.clearCollection", "Koleksiyonu Temizle"},
                {"main.menu.countTicketsThat", "Åundan daha az indirimli biletleri sayÄ±n..."},
                {"main.menu.printDiscount", "TÃ¼m indirim deÄerlerini yazdÄ±r"},
                {"main.menu.uniquePrice", "Benzersiz fiyat deÄerleri"},
                {"main.menu.infoAboutCollection", "Koleksiyon Bilgileri"},
                {"main.commandMenu", "TakÄ±mlar"},
                {"main.helpMenu", "YardÄ±m"},
                {"main.help.help", "Komut listesini yazdÄ±r"},
                {"main.filterByColumnLabel", "TarafÄ±ndan filtre:"},
                {"main.refreshTableButton", "Yenile"},
                {"main.currentUserLabel", "Åu anki kullanÄ±cÄ±:"},
                {"edit.header", "Bilet dÃ¼zenleme"},
                {"edit.ticketName", "Bilet adÄ±:"},
                {"edit.ticketX", "X koordinatÄ±"},
                {"edit.ticketY", "Y koordinatÄ±"},
                {"edit.ticketPrice", "Fiyat"},
                {"edit.ticketDiscount", "Ä°ndirim"},
                {"edit.ticketType", "bilet tipi"},
                {"edit.eventName", "Etkinlik adÄ±"},
                {"edit.eventDate", "Etkinlik tarihi"},
                {"edit.eventMinAge", "Asgari yaÅ"},
                {"edit.eventDescription", "olayÄ±n aÃ§Ä±klamasÄ±"},
                {"edit.eventType", "Etkinlik tipi"},
                {"edit.saveTicketIfMinButton", "Bilet minimumsa kaydet"},
                {"edit.saveTicketButton", "Bileti kaydet"},
                {"edit.alerts.blankFieldError", "GÃ¶rÃ¼nÃ¼Åe gÃ¶re tÃ¼m form alanlarÄ±nÄ± doldurmamÄ±ÅsÄ±nÄ±z. Tekrar deneyin."},
                {"edit.ticketComment", "Bir yorum"},
                {"auth.alerts.authError", "Yetkilendirme HatasÄ±"},
                {"main.alerts.error", "bir hata oluÅtu "},
                {"main.alerts.success", "BaÅarÄ±yla!"},
                {"main.collectionType", "Koleksiyon tÃ¼rÃ¼"},
                {"main.initializationDate", "BaÅlatma tarihi: "},
                {"main.itemsQuantity", "ÃÄe miktarÄ±:"},
                {"main.alerts.discountQuantity", "Ä°ndirim deÄerini girin: "},
                {"main.alerts.notNumber", "DeÄer bir sayÄ± deÄil!"},
                {"main.alerts.discountError", "DeÄer, indirim aralÄ±ÄÄ±na uymuyor"},
                {"main.ticketEditing", "Bilet deÄiÅikliÄi"},
                {"main.alerts.fieldsError", "BazÄ± form alanlarÄ± hatalÄ± doldurulmuÅtur."},
                {"main.mainWindow", "Ana pencere"},
                {"auth.alerts.serverConnectionError", "Sunucuya baÄlanÄ±rken bir hata oluÅtu "},
                {"auth.alerts.serverConnectionSuccess", "Sunucuya baÄlantÄ± baÅarÄ±lÄ± oldu!"},
                {"auth.serverConnection", "sunucu baÄlantÄ±sÄ±"},
                {"drawing.windowTitle", "Mevcut durumun gÃ¶rselleÅtirilmesi"},
                {"main.menu.changeUserColors", "Tablo renklerini gÃ¼ncelle"},
                {"edit.deleteTicketButton", "Silmek"},
                {"main.addIfMin", "Minimum ise bilet ekleyin"},
                {"main.executeScript", "Komut dosyasını çalıştır"}
        };
    }
}
